name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn test --ci --coverage
      - run: yarn test:e2e --ci --coverage --maxWorkers=1

  # deploy:
  #   name: Deploy to Render
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
