name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
